### ISSUE TITLE
demo application

### ISSUE THREAD

**Issue by pdurbin** [FelipeKatao/Py.Html#11]
I'd like to suggest that you create a demo application to show how Py.Html is used.

For example, lots of frameworks contribute demo applications to http://todomvc.com as in the screenshot below.

The idea is that my looking at the code for a demo application, I can get a good idea of if I like the framework or not.

<img width="1260" alt="Screen Shot 2019-06-02 at 9 25 44 AM" src="https://user-images.githubusercontent.com/21006/58762017-d6be0f00-8518-11e9-863a-fe77e367091e.png">

**Comment by FelipeKatao** [comment]
Okay, I'll create a demo for our framework and you'll see and understand better how to use Py.html. And if you want to be part of the project and help it grow

**Comment by FelipeKatao** [comment]
Hello, i create one exemple basic with **Py.Htm**l see result final:
![image](https://user-images.githubusercontent.com/34559081/58763772-c7998a00-8535-11e9-8546-90e9ce29f8a1.png)
With few lines i create one pretty site with elements cool, without code the html 
Exemple code this one:  https://github.com/FelipeKatao/Py.Html/tree/master/DemoAplication
I'm waiting for your feedback, thank you!

**Comment by pdurbin** [comment]
@FelipeKatao thanks I cloned the repo and edited `main.py` and ran it to regenerate `app.html`. The framework makes more sense to me. Thanks again. I'll close this issue.
