### ISSUE TITLE
Component Menu Don´t exists

### ISSUE THREAD

**Issue by FelipeKatao** [FelipeKatao/Py.Html#15]
Create one menu with JavaScipt and Bootstrap Framework, create its elements in path **Components.**

**Comment by sivakumarjsl** [comment]
How can run application.plz help me start things

**Comment by FelipeKatao** [comment]
Sorry, for the delay @sivakumarjsl , int this file your can edit and create one menu with JavaScript and Css , edit this document file https://github.com/FelipeKatao/Py.Html/blob/master/Framework/Components/menuBar.html

**Comment by FelipeKatao** [comment]
https://github.com/FelipeKatao/Py.Html/blob/master/Framework/Components/js/menubar.js
this is one template for you, create the **JavaScript**  code , the menu via javaScript must have change color when hover, drop menu and interactive menu with user.

**Comment by sivakumarjsl** [comment]
I don't know how to do run the app. . Anything I need to install

**Comment by FelipeKatao** [comment]
https://github.com/FelipeKatao/Py.Html/tree/master/Framework/ReactModel
Run the App in this folder path

**Comment by sivakumarjsl** [comment]
Okay thanks . I will take a look . Work on that.

**Comment by sivakumarjsl** [comment]
Am commit change in master branch please take a look.

**Comment by FelipeKatao** [comment]
I look your Work Siva, great work! I closed its issue friend!

**Comment by sivakumarjsl** [comment]
Thanks buddy. We need to change anything there ya.

**Comment by sivakumarjsl** [comment]
Dear friend,
        You will create PayPal account to transfer the international money
easily.once you create the  account and let me know buddy. I send some
details also in slack about PayPal. Please take a look at it.

**Comment by sivakumarjsl** [comment]
Hi friend,
       You will create a PayPal account to transfer money.please see a
slack messages.
