### ISSUE TITLE
Create new functions for console Py.Html

### ISSUE THREAD

**Issue by FelipeKatao** [FelipeKatao/Py.Html#22]
**Create news functions for PyHtmlConsole.py**
_Targets:_ https://github.com/FelipeKatao/Py.Html/blob/master/PyHtmlConsole.py  and  https://github.com/FelipeKatao/Py.Html/blob/master/Framework/StyleTools.py

*How add new function for console Py.Html*
First add the new command to the command list in the **PyHtmlConsole.py** module.
`LISTCOMMAND= ["help","create.html","exit","create.html.menu","create.html.form","set.path","link.css","create.element","create.html.responsive"]`

After inside the ExecuteCommand method, add an if with the new command you created.
`if command == "create.html.form":
        pass`

Following are the commands you should add to the list and variable:

- [x] create.css
- [x] create.css.rule.class
- [x] create.css.rule.id
- [x] responsive.create

After creating these commands, later we will implement their use.

**Comment by FelipeKatao** [comment]
Now _implement the functions_ you created in the console within the **https://github.com/FelipeKatao/Py.Html/blob/master/Framework/StyleTools.py** file.
Has all the methods to work inside the console.

Within ifs put another if to detect if the location has been set:
`  if(dt._localHtmlFiles[con._SETFILE]!="0"):
         else:`

Attach at the end of each if and within each else a print on the screen to show that the operation was successful:
`print("Css file was created successfully") `
Customize the message according to the operation that was done

**Comment by FelipeKatao** [comment]
For example: 
`  if command == "link.css":
         if(dt._localHtmlFiles[con._SETFILE]!="0"):
            print("Css Link anexed with susefull")             
            pass
         else:
            print("Css Link anexed with susefull")
            pass`

**Comment by paulinhomacedo** [comment]
Done man!

**Comment by FelipeKatao** [comment]
Closed the Issue @PauloAMacedo
